// Generated by CoffeeScript 1.3.3
var app, express, io, localTime, padStr, server, socket;

express = require('express');

socket = require('socket.io');

app = express();

server = app.listen(8080);

io = socket.listen(server);

app.set('view engine', 'jade');

app.set('views', 'views/');

app.use('/', express["static"](__dirname + '/public'));

app.get('/:page', function(req, res) {
  return res.render(req.params.page);
});

app.get('/', function(req, res) {
  return res.render('home');
});

padStr = function(i) {
  if (i < 10) {
    return "0" + i;
  } else {
    return "" + i;
  }
};

localTime = function() {
  var curDate, time;
  curDate = new Date();
  return time = {
    string: padStr(curDate.getHours()) + ':' + padStr(curDate.getMinutes()) + ':' + padStr(curDate.getSeconds()),
    hour: curDate.getHours()
  };
};

io.sockets.on('connection', function(client) {
  console.log(localTime().string + ' - New connection');
  client.on('message', function(data) {
    return client.get('cdata', function(err, cdata) {
      client.broadcast.emit('newmsg', {
        nick: cdata.nickname,
        msg: data.msg
      });
      client.emit('newmsg', {
        nick: cdata.nickname,
        msg: data.msg
      });
      return console.log(localTime().string + ' - ' + cdata.nickname + ': ' + data.msg);
    });
  });
  return client.on('join', function(data) {
    var offset;
    offset = data.localHour - localTime().hour;
    client.set('cdata', {
      nickname: data.nickname
    });
    client.emit('sysmsg', 'Hallo, <b>' + data.nickname + '</b>!');
    client.broadcast.emit('sysmsg', '<b>' + data.nickname + '</b> connected');
    return console.log(localTime().string + ' - ' + data.nickname + ' connected.');
  });
});
